### ISSUE TITLE
FEATURE REQUEST: O3 with sneaky OSD Fonts - Can u fix, what DJI never does?

### ISSUE THREAD

**Issue by fellpower** [fpv-wtf/wtfos#79] opened 2023-05-27 13:21 UTC
As i know, the idea to "hack" the O3 is not there.

BUT - why we cant get that sneaky osd fonts working? MSP works sometimes - but not with custom OSD Fonts.

Maybe we can get this "fix" only? ;)

HAM and so on is working, HD OSD too with INAV - not really, because its a BF "copy" - no real INAV OSD - because with the BF fix, were sooo limited in Symbols and so on.

But no custom Fonts. thats pity :(

Is there any work, that can get spend on this?

**Comment by j005u** [comment] 2023-06-13 13:43
There's nothing we can do about fonts without rooting the system first.

There is currently nothing to announce on that front. Closing this issue as it's a duplicate of #45.

**Closed by j005u** 2023-06-13 13:43 UTC
