### ISSUE TITLE
Video out breaks with WTFOS

### ISSUE THREAD

**Issue by j005u** [fpv-wtf/wtfos#15] opened 2022-08-15 13:22 UTC
Scattered reports (including myself having some issues) of video out becoming unusable/unstable with wtfos.

Need to investigate.

**Comment by bri3d** [comment] 2022-10-03 19:40
@j005u Should we close this issue?

We investigated this issue and determined that, as far as we can tell, this was always caused by Windows driver issues.

**Closed** 2022-10-05 16:56 UTC
